/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author claudioalmeida
 */
public class LoginView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Logo_login = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Digitar_Nome_usuario = new javax.swing.JTextField();
        Nome_user_tela = new javax.swing.JLabel();
        javax.swing.JTextField Inserir_senha = new javax.swing.JTextField();
        Digite_senha = new javax.swing.JLabel();
        Mostrar_senha = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuUsuario = new javax.swing.JMenu();
        MenuCadastroUsuario = new javax.swing.JMenuItem();
        javax.swing.JMenuItem MenuAlterarusuario = new javax.swing.JMenuItem();
        MenuAtivo = new javax.swing.JMenu();
        MenuAtivoCadastrar = new javax.swing.JMenuItem();
        javax.swing.JMenuItem MenuAtivoDepreciacao = new javax.swing.JMenuItem();
        MenuAtivoValorJusto = new javax.swing.JMenuItem();
        MenuCliente = new javax.swing.JMenu();
        MenuClienteCadastrar = new javax.swing.JMenuItem();
        javax.swing.JMenuItem MenuClienteExcluir = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        MenuRelatoriosAtivo = new javax.swing.JMenu();
        MenuRelatoriosAtivosValorJusto = new javax.swing.JMenuItem();
        MenuIndice = new javax.swing.JMenu();
        MenuIndiceIPCA = new javax.swing.JMenuItem();
        javax.swing.JMenuItem MenuIndiceIGPM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setMaximizedBounds(getMaximizedBounds());
        setState(getExtendedState());
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image/Fundo-de-sistema.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 670, 540);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jPanel1.setLayout(null);

        Logo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/face.png"))); // NOI18N
        jPanel1.add(Logo_login);
        Logo_login.setBounds(60, 70, 0, 108);

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        jPanel1.add(Login);
        Login.setBounds(56, 13, 151, 45);

        Digitar_Nome_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digitar_Nome_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Digitar_Nome_usuario);
        Digitar_Nome_usuario.setBounds(24, 190, 215, 31);

        Nome_user_tela.setBackground(new java.awt.Color(255, 255, 255));
        Nome_user_tela.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Nome_user_tela.setForeground(new java.awt.Color(255, 255, 255));
        Nome_user_tela.setText("Nome do Usuario:");
        jPanel1.add(Nome_user_tela);
        Nome_user_tela.setBounds(30, 227, 142, 18);

        Inserir_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir_senhaActionPerformed(evt);
            }
        });
        jPanel1.add(Inserir_senha);
        Inserir_senha.setBounds(24, 257, 215, 31);

        Digite_senha.setBackground(new java.awt.Color(255, 255, 255));
        Digite_senha.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Digite_senha.setForeground(new java.awt.Color(255, 255, 255));
        Digite_senha.setText("Digite a sua senha:");
        jPanel1.add(Digite_senha);
        Digite_senha.setBounds(24, 300, 142, 18);

        Mostrar_senha.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Mostrar_senha.setForeground(new java.awt.Color(255, 255, 255));
        Mostrar_senha.setText("Mostrar Senha");
        Mostrar_senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Mostrar_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_senhaActionPerformed(evt);
            }
        });
        jPanel1.add(Mostrar_senha);
        Mostrar_senha.setBounds(24, 330, 125, 23);
        Mostrar_senha.getAccessibleContext().setAccessibleParent(this);

        jButton1.setText("Entrar");
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 380, 78, 23);

        jButton2.setText("Realizar Cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 440, 150, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 100, 280, 500);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        MenuUsuario.setBackground(new java.awt.Color(153, 153, 153));
        MenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone_usuarios.png"))); // NOI18N
        MenuUsuario.setText("Usuario");
        MenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuarioActionPerformed(evt);
            }
        });

        MenuCadastroUsuario.setText("Cadastro");
        MenuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroUsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(MenuCadastroUsuario);

        MenuAlterarusuario.setText("Alterar");
        MenuUsuario.add(MenuAlterarusuario);

        jMenuBar1.add(MenuUsuario);

        MenuAtivo.setBackground(new java.awt.Color(153, 153, 153));
        MenuAtivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone_ativo_c.png"))); // NOI18N
        MenuAtivo.setText("Ativo");

        MenuAtivoCadastrar.setText("Cadastrar");
        MenuAtivo.add(MenuAtivoCadastrar);

        MenuAtivoDepreciacao.setText("Calcular Depreciacao");
        MenuAtivoDepreciacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtivoDepreciacaoActionPerformed(evt);
            }
        });
        MenuAtivo.add(MenuAtivoDepreciacao);

        MenuAtivoValorJusto.setText("Calcular Valor Justo");
        MenuAtivo.add(MenuAtivoValorJusto);

        jMenuBar1.add(MenuAtivo);

        MenuCliente.setBackground(new java.awt.Color(153, 153, 153));
        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone_Cliente.png"))); // NOI18N
        MenuCliente.setText("Cliente");

        MenuClienteCadastrar.setText("Cadastrar");
        MenuCliente.add(MenuClienteCadastrar);

        MenuClienteExcluir.setText("Excluir");
        MenuClienteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteExcluirActionPerformed(evt);
            }
        });
        MenuCliente.add(MenuClienteExcluir);

        jMenuBar1.add(MenuCliente);

        MenuRelatorios.setBackground(new java.awt.Color(153, 153, 153));
        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone_report.png"))); // NOI18N
        MenuRelatorios.setText("Relatorios");

        MenuRelatoriosAtivo.setText("Relatorios Ativos");
        MenuRelatorios.add(MenuRelatoriosAtivo);

        MenuRelatoriosAtivosValorJusto.setText("Relatorio Ativo Valor Justo");
        MenuRelatorios.add(MenuRelatoriosAtivosValorJusto);

        jMenuBar1.add(MenuRelatorios);

        MenuIndice.setBackground(new java.awt.Color(153, 153, 153));
        MenuIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icone_custo.png"))); // NOI18N
        MenuIndice.setText("Indices");

        MenuIndiceIPCA.setText("Indices IPCA");
        MenuIndiceIPCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIndiceIPCAActionPerformed(evt);
            }
        });
        MenuIndice.add(MenuIndiceIPCA);

        MenuIndiceIGPM.setText("Indices IGPM");
        MenuIndiceIGPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIndiceIGPMActionPerformed(evt);
            }
        });
        MenuIndice.add(MenuIndiceIGPM);

        jMenuBar1.add(MenuIndice);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void MenuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCadastroUsuarioActionPerformed

    private void Digitar_Nome_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digitar_Nome_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Digitar_Nome_usuarioActionPerformed

    private void Inserir_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inserir_senhaActionPerformed

    private void Mostrar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mostrar_senhaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MenuClienteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuClienteExcluirActionPerformed

    private void MenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUsuarioActionPerformed

    private void MenuAtivoDepreciacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtivoDepreciacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAtivoDepreciacaoActionPerformed

    private void MenuIndiceIPCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIndiceIPCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIndiceIPCAActionPerformed

    private void MenuIndiceIGPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIndiceIGPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuIndiceIGPMActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Digitar_Nome_usuario;
    private javax.swing.JLabel Digite_senha;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Logo_login;
    private javax.swing.JMenu MenuAtivo;
    private javax.swing.JMenuItem MenuAtivoCadastrar;
    private javax.swing.JMenuItem MenuAtivoValorJusto;
    private javax.swing.JMenuItem MenuCadastroUsuario;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenuItem MenuClienteCadastrar;
    private javax.swing.JMenu MenuIndice;
    private javax.swing.JMenuItem MenuIndiceIPCA;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuRelatoriosAtivo;
    private javax.swing.JMenuItem MenuRelatoriosAtivosValorJusto;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JCheckBox Mostrar_senha;
    private javax.swing.JLabel Nome_user_tela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
